/* Generated By:JavaCC: Do not edit this line. TemplateConstants.java */
package com.hoiio;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TemplateConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR = 4;
  /** RegularExpression Id. */
  int ALPHANUM = 5;
  /** RegularExpression Id. */
  int OCURL = 6;
  /** RegularExpression Id. */
  int CCURL = 7;
  /** RegularExpression Id. */
  int OPAR = 8;
  /** RegularExpression Id. */
  int CPAR = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int OTHER = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<VAR>",
    "<ALPHANUM>",
    "<OCURL>",
    "<CCURL>",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "<OTHER>",
  };

}
